services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./docker-data/qdrant-data:/qdrant/storage
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.5
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - fastapi-app
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.6.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./config/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
    restart: unless-stopped
