{
 "title": "Epitome Academy Recommendation System",
 "time": { "from": "2025-07-14T21:35:38.967Z", "to": "2025-07-14T21:37:14.913Z" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Duration (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}