global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'soufianeelassrii@gmail.com'
  smtp_auth_username: 'soufianeelassrii@gmail.com'
  smtp_auth_password: 'aqls rvzn xqjf rkyo'

route:
  receiver: 'email-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'soufianeelassrii@gmail.com'
        send_resolved: true
        text: |
          Alert: {{ .GroupLabels.alertname }}
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}