groups:
- name: epitome_academy_alerts
  rules:
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is above 2 seconds for more than 5 minutes."

  - alert: HighErrorRate
    expr: |
      sum(rate(http_requests_total{code=~"5.."}[5m])) 
      / 
      sum(rate(http_requests_total[5m])) 
      > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 5% for more than 5 minutes."

  - alert: HighProcessMemoryUsage
    expr: process_resident_memory_bytes > 6 * 1024 * 1024 * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High process memory usage detected"
      description: "App process is using more than 6 GiB RAM for more than 5 minutes."

  - alert: HighProcessDiskUsage
    expr: process_virtual_memory_bytes > 20 * 1024 * 1024 * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High process disk usage detected"
      description: "App process is using more than 20 GiB of virtual memory for more than 5 minutes." 